// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drqcnssxwwvxijbgncsz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRycWNuc3N4d3d2eGlqYmduY3N6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNTQ3OTksImV4cCI6MjA1ODkzMDc5OX0.160YmJ5nHojwujvdqyPVwwqYndQkQJjMFmw7R7yb104";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);